CREATE DATABASE `setaria` CHARACTER SET utf8 COLLATE utf8_bin ;
USE `setaria` ;

-- create user --
CREATE USER 'setaria' @'%' IDENTIFIED BY 'setaria' ;

FLUSH PRIVILEGES ;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE
ON `setaria`.*
TO 'setaria' @'%'
WITH GRANT OPTION ;
